eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultUrl:
        defaultZone: http://localhost:8787/eureka
  instance:
    hostname: localhost
server:
  port: 8888
spring:
    application:
      name: payment-service
